### ISSUE TITLE
你好，想请问关于deepmot你用自己的数据训练了吗（除mot17）

### ISSUE THREAD

**Issue by yanfg1** [wangxianrui/mot-sst#1]

**Comment by wangxianrui** [comment]
没有, 他那个太慢了

**Comment by yanfg1** [comment]
那想请问一下，如果用基于单目标跟踪器的多目标跟踪来训练车辆跟踪的话，有什么推荐吗，老师布置任务最近让做一个这样的小demo出来，但是没有思路了

**Comment by wangxianrui** [comment]
单目标的话你可以看看pysot `https://github.com/STVIR/pysot`, siam系列效果比较好, 
单目标应用到多目标开源的有dman `https://github.com/jizhu1023/DMAN_MOT` 开源的好像不是很多

**Comment by yanfg1** [comment]
非常谢谢了
